server:
  port: 80 #localhost <=> 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9090 #localhost:9090/api/v1/auth/find-all
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/auth-service

        - id: user-profile-service
          predicates:
            - Path=/user-profile/**
          uri: http://localhost:9080
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user-profile-service
        - id: company-service
          predicates:
            - Path=/company/**
          uri: http://localhost:9070
        - id: company-service-comment
          predicates:
            - Path=/comment/**
          uri: http://localhost:9070
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/company-service
        - id: mail-service
          predicates:
            - Path=/mail/**
          uri: http://localhost:9075
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mail-service
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}

