server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: efe
    password: 123

  zipkin:
    enabled: false
    base-url: http://localhost:9411
    service:
      name: mail-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${java9mail}
    password: ${java9mailpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  auth-exchange: authExchange
  mail-binding-key: mailKey
  mail-queue: mailQueue
  registerMailQueue: mail-queue
  registerMailHelloQueue: mail-hello-queue