server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${HRM-Mail}
    password: ${HRM-Mail-Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretkey: ${secretkey}
  udience: ${audience}
  issuer: ${issuer}

rabbitmq:
  queueForgotPassword: forgot-password-mail-queue
  registerMailQueue: mail-queue
  registerMailHelloQueue: mail-hello-queue
  queueResetPassword: reset-password-mail-queue
  queuePersonnelPassword: queue-personnel-password
  queueManagerChangeStatus: queue-manager-change-status