server:
  port: 9093

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/UserProfileDb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  user-exchange: user-exchange
  personnelPasswordKey: personnel-password-key
  queuePersonnelPassword: queue-personnel-password
  managerChangeStatusKey: manager-change-status-key
  queueManagerChangeStatus: queue-manager-change-status